Updating per review

diff --git a/levistate b/levistate
--- a/levistate
+++ b/levistate
@@ -36,56 +36,55 @@ getHostOperatingSystem() {
 
 	stat /etc/os-release > /dev/null 2> /dev/null
     
-    if [ $? -ne 0 ] 
-    then
+	if [ $? -ne 0 ] 
+	then
 		osRelease=$NON_LINUX
 	fi 
 		
 }
 
 getMaxContainerVersion() {
-    if [ ! -z $IMAGE_TAG ]
-    then
-        maxContainerVersion=$IMAGE_TAG
-    else
-        versions=`docker images | grep $metroAEImage | awk '{ print $2}'`
-        maxContainerVersion=''
-        for version in $versions
-        do
-            if [ -z $maxContainerVersion ]
-            then
-                    maxContainerVersion=$version
-            fi
-    
-            if [ $maxContainerVersion \< $version ]
-            then
-                    maxContainerVersion=$version
-            fi
-        done
-    
-        if [ -z $maxContainerVersion ]
-        then
-            maxContainerVersion='current'
-        fi
-    fi
+	if [ ! -z $IMAGE_TAG ]
+	then
+		maxContainerVersion=$IMAGE_TAG
+	else
+        	versions=`docker images | grep $metroAEImage | awk '{ print $2}'`
+        	maxContainerVersion=''
+        	for version in $versions
+        	do
+            		if [ -z $maxContainerVersion ]
+            		then
+                    		maxContainerVersion=$version
+            		fi
 
-    echo "Max Container version detected $maxContainerVersion" >> ./metroae.log
+	                if [ $maxContainerVersion \< $version ]
+            		then
+                    		maxContainerVersion=$version
+            		fi
+        	done
 
+        	if [ -z $maxContainerVersion ]
+	        then
+           		 maxContainerVersion='current'
+        	fi
+    	fi
+
+	echo "Max Container version detected $maxContainerVersion" >> ./metroae.log
 }
 
 getContainerID() {
-    getMaxContainerVersion
-    containerID=`docker ps -a | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
+	getMaxContainerVersion
+	containerID=`docker ps -a | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
 }
 
 getRunningContainerID() {
-    getMaxContainerVersion
-    runningContainerID=`docker ps | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
+	getMaxContainerVersion
+	runningContainerID=`docker ps | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
 }
 
 getImageID() {
-    getMaxContainerVersion
-    imageID=`docker images | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $3}'`
+	getMaxContainerVersion
+	imageID=`docker images | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $3}'`
 }
 
 
@@ -224,19 +223,19 @@ destroy() {
 
 getFromS3()
 {
-  file=metroaecontainer.tar
-  aws_path=/images/
-  bucket='nuage-devops'
-  date=$(date +"%a, %d %b %Y %T %z")
-  content_type='application/x-compressed-tar'
-  string="GET\n\n$content_type\n$date\n/$bucket$aws_path$file"
-  signature=$(echo -en "${string}" | openssl sha1 -hmac "${S3SECRET}" -binary | base64)
-  curl -X GET\
-    -H "Host: $bucket.s3.amazonaws.com" \
-    -H "Date: $date" \
-    -H "Content-Type: $content_type" \
-    -H "Authorization: AWS ${S3KEY}:$signature" \
-    "https://$bucket.s3.amazonaws.com$aws_path$file" > $temp$file | tee -a ./metroae.log 2>> ./metroae.log
+	file=metroaecontainer.tar
+	aws_path=/images/
+	bucket='nuage-devops'
+	date=$(date +"%a, %d %b %Y %T %z")
+	content_type='application/x-compressed-tar'
+	string="GET\n\n$content_type\n$date\n/$bucket$aws_path$file"
+	signature=$(echo -en "${string}" | openssl sha1 -hmac "${S3SECRET}" -binary | base64)
+	curl -X GET\
+  	-H "Host: $bucket.s3.amazonaws.com" \
+  	-H "Date: $date" \
+  	-H "Content-Type: $content_type" \
+  	-H "Authorization: AWS ${S3KEY}:$signature" \
+  	"https://$bucket.s3.amazonaws.com$aws_path$file" > $temp$file | tee -a ./metroae.log 2>> ./metroae.log
 }
 
 pull() {
@@ -291,7 +290,7 @@ getUserPathInput() {
 		validPath=$?
 		if [ $validPath -ne 0 ]
 		then
-			echo "Invalid path provided"
+			echo "Path not found"
 		fi
 
 		# check to see if the path ends with passed in directory
@@ -314,8 +313,8 @@ setup() {
 	then
 		echo "You already have the MetroÆ container set up. Running setup will destroy the"
 		echo "existing container and create a new one. Your data on disk will be preserved."
-		echo "If you continue, create the new container, and use the same data and image"
-		echo "mount points, no changes are required. If you change the mount points, however"
+		echo "If you continue, create the new container, and use the same data"
+		echo "mount point, no changes are required. If you change the mount points, however"
 		echo "you will need to copy your existing data to the new mount points."
 
 		confirmation="init"
